### ISSUE TITLE
Make a general function for all splitting strategies.

### ISSUE THREAD

**Issue by DomInvivo** [datamol-io/splito#8]
Similar to the [sklearn.train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) method, implement another function `general_split` or `train_test_split` that does any kind of splitting.

```python
def general_split(
    mols: Union[datamol.Mol, str], 
    test_size: Union[float, int], 
    splitting_method: Literal["random", "scaffold", "kmeans"], 
    random_state: int = 42, 
    n_jobs:int=0, 
    *args, 
    **kwargs)

    print("Do some magic")
    return train_idx, test_idx
```

**Comment by cwognum** [comment]
@DomInvivo Sorry for taking a while to address this, but I made a PR that should address this in #12 . Could you let me know what you think of the new API? Does this meet your expectations?
